@startuml
title Object Diagram HW2 - Part 2
object "<u>Titanic: Ship</u>" as titanic{
    shipName = "Titanic"
    yearBuilt = "March31st, 1909"
}

object "<u>MVGemini: CruiseShip</u>" as mvGemini{
    shipName = "MVGemini"
    yearBuilt = "May30th, 1991"
    maxNumberPassengers= 100
}
object "<u>EverGiven: CargoShip</u>" as everGiven{
    shipName = "EverGiven"
    yearBuilt = "September25th, 2018"
    cargoCapacity = 220940
}

object "<u>ships: Ship[]</u>" as ships {
    ships = [titanic, mvGemini, everGiven]
}

ships --> titanic
ships --> mvGemini
ships --> everGiven

newpage
object "<u>c1Instructor: Instructor</u>" as c1Instructor{
    firstName = "Nima"
    lastName = "Davarpanah"
    officeNumber = "3-2636"
}

object "<u>c1Textbook: Textbook</u>" as c1Textbook{
    title = "CleanCode: A Handbook of Agile Software Craftsmanship"
    author = "Robert C. Martin"
    publisher = "Pearson"
}

object "<u>c1: Course</u>" as c1{
    name= "CS5800 - Advanced Software Engineering"
    instructor = c1Instructor
    textbook = c1Textbook
}

c1 o-- c1Instructor
c1 o-- c1Textbook

object "<u>phpDemo1: Folder</u>" as phpDemo1{
    name= "php_demo1"
    subFolders = [src, includePath, remoteFiles]
}

object "<u>IncludePath: Folder</u>" as includePath{
    name="Include Path"
}

object "<u>RemoteFiles: Folder</u>" as remoteFiles{
    name= "Remote Files"
}
object "<u>SourceFiles: Folder</u>" as src{
    name= "Source Files"
    subFolders = [phalcon, cache, publicF]
}

object "<u>.phalcon: Folder</u>" as phalcon{
    name= ".phalcon"   
}

object "<u>cache: Folder</u>" as cache{
    name= "cache"
}

object "<u>public: Folder</u>" as publicF{
    name= "public"
    files=[".htaccess", ".htrouter.php", "index.html"]
}

phpDemo1 --> src
phpDemo1 --> includePath
phpDemo1 --> remoteFiles
src --> phalcon
src --> cache
src --> publicF
@enduml